### ISSUE TITLE
--no-gitsvn issues on nested externals

### ISSUE THREAD

**Issue by faism** [develersrl/git-externals#11]
There is a problem when using the `--no-gitsvn` flag on a repository that contains nested externals.
Each _first level_ external is downloaded in the .git/externals directory using the `svn checkout` command, and a symbolic link pointing to it is created in the right place. Each _second level_ external is then downloaded in the .git/externals directory inside the _first level_ external working directory. But when the script tries to create a symbolic link to the _second level_ externals an error occurs, because the checkout of a svn repository already includes the checkout of its externals.

To show where the problem is, consider having a test project called my_project which includes an external component called foo, which in turn includes another external component called bar.
Here is a traceback of the error you get when executing a git externals update.

`Traceback (most recent call last):`
`  File "/home/faism/.local/bin/git-externals", line 11, in <module>`
`    sys.exit(cli())`
`  File "/home/faism/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__`
`    return self.main(*args, **kwargs)`
`  File "/home/faism/.local/lib/python2.7/site-packages/click/core.py", line 697, in main`
`    rv = self.invoke(ctx)`
`  File "/home/faism/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke`
`    return _process_result(sub_ctx.command.invoke(sub_ctx))`
`  File "/home/faism/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke`
`    return ctx.invoke(self.callback, **ctx.params)`
`  File "/home/faism/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke`
`    return callback(*args, **kwargs)`
`  File "/home/faism/.local/lib/python2.7/site-packages/git_externals/cli.py", line 118, in gitext_update`
`    gitext_up(recursive, reset=reset, use_gitsvn=gitsvn)`
`  File "/home/faism/.local/lib/python2.7/site-packages/git_externals/git_externals.py", line 380, in gitext_up`
`    gitext_up(recursive, entries, reset=reset, use_gitsvn=use_gitsvn)`
`  File "/home/faism/.local/lib/python2.7/site-packages/git_externals/git_externals.py", line 372, in gitext_up`
`    link_entries(git_externals)`
`  File "/home/faism/.local/lib/python2.7/site-packages/git_externals/git_externals.py", line 213, in link_entries`
`    rm_link(dst)`
`OSError: [Errno 21] Is a directory: '/home/faism/devel/projects/my_project/.git/externals/foo/lib/bar'`

**Comment by arl** [comment]
Ok, so basically the fix could be to pass `--ignore-externals` when perfoming an `svn checkout`, right?

**Comment by arl** [comment]
Fixed in #12
