### ISSUE TITLE
If no remote "origin" is configured git externals update fails

### ISSUE THREAD

**Issue by aleph6502** [develersrl/git-externals#13]
Trying "git externals update" on a repository with no remote "origin" configured, I obtain the following:

`externals sanity check passed!`
`<GitError: 1 "git config remote.origin.url" >`

Adding any origin solves the problem.

**Comment by arl** [comment]
Do you mean that a remote called "origin"  must absolutely be defined? Or
that at least one remote, however called, must be defined?

Le 21 févr. 2017 09:31, "Stefano Fedrigo" <notifications@github.com> a
écrit :
