### ISSUE TITLE
Handle `svn:r` syntax to specify revision

### ISSUE THREAD

**Issue by arl** [develersrl/git-externals#7]
The  `svn:r` syntax is used to specify svn revision to a clone done with `git-svn`, so as to differentiate it from a git SHA. In order to be consistent, this syntax should also be handled by clones made with svn

**Comment by naufraghi** [comment]
@aurelien-rainone maybe resolved by #8?

**Comment by naufraghi** [comment]
Done in PR #18: [git_externals.py](https://github.com/develersrl/git-externals/pull/18/files#diff-e31058e187467ea3673de2f3207b8659R258)
